name: server-docker

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64v8]
    runs-on: >-
      ${{ fromJson('{ "amd64": "ubuntu-24.04", "arm64v8": "ubuntu-24.04-arm" }')[matrix.arch] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          context: ./server/
          tags: ghcr.io/peat-psuwit/gst-webrtc-transcoder-server:latest-${{ matrix.arch }}
          outputs: type=docker,dest=${{ runner.temp }}/server_${{ matrix.arch }}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: server_${{ matrix.arch }}
          path: ${{ runner.temp }}/server_${{ matrix.arch }}.tar

  push:
    runs-on: ubuntu-24.04
    if: >
      ${{ github.repository == 'peat-psuwit/gst-webrtc-transcoder-server' &&
          github.ref == 'refs/heads/main' }}
    needs: [ build ]
    permissions:
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}
          pattern: server_*
          merge-multiple: true

      - name: Load images, create manifest, and push images
        run: |
          set -x
          docker load --input ${{ runner.temp }}/server_amd64.tar
          docker load --input ${{ runner.temp }}/server_arm64v8.tar

          docker push \
            ghcr.io/peat-psuwit/gst-webrtc-transcoder-server:latest-amd64
          docker push \
            ghcr.io/peat-psuwit/gst-webrtc-transcoder-server:latest-arm64v8

          docker manifest create \
            ghcr.io/peat-psuwit/gst-webrtc-transcoder-server:latest \
              --amend ghcr.io/peat-psuwit/gst-webrtc-transcoder-server:latest-amd64 \
              --amend ghcr.io/peat-psuwit/gst-webrtc-transcoder-server:latest-arm64v8

          docker manifest push ghcr.io/peat-psuwit/gst-webrtc-transcoder-server:latest
